
const GET_STRATEGY_LIST ='GET_STRATEGY_LIST'
const GET_STRATEGY_DETAIL = 'GET_STRATEGY_DETAIL'
const UPDATE_STRATEGY_DETAIL = 'UPDATE_STRATEGY_DETAIL'
export const strategyConstants = {
    GET_STRATEGY_LIST,
    GET_STRATEGY_DETAIL,
    UPDATE_STRATEGY_DETAIL
}